### ISSUE TITLE
CMAKE build support for riscv-llvm

### ISSUE THREAD

**Issue by lmchale** [ucb-bar/esp-llvm#10]
Building riscv-llvm using cmake does not automatically detect support for riscv as a target.  Please update cmake configuration to add in build support for riscv-llvm.

**Comment by neuschaefer** [comment]
Which branch are you using?

In riscv-trunk it should now work (since bc79b8b7).

**Comment by colinschmidt** [comment]
Please reopen this issue if you have still have trouble on the riscv-trunk or the riscv-37 branches with CMAKE
