### ISSUE TITLE
A Travis-CI button

### ISSUE THREAD

**Issue by neuschaefer** [ucb-bar/esp-llvm#21]
Hi, I'm an independent open source guy.

For visibility of our continuous testing efforts, I'd like to have a Travis-CI button. A question comes up, though: Which branch should it track?

**Comment by colinschmidt** [comment]
I believe that travis is nearly setup (https://travis-ci.org/riscv/riscv-llvm/branches). I think the riscv-37 and riscv-trunk branches are the most likely to be able to robustly pass CI going forward.

**Comment by neuschaefer** [comment]
Ok.
